### ISSUE TITLE
ToTable VI No Longer Matches NISE_CEF_serializable node Class Method

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/SharedMemoryModule#4]
Add "row headers" array output terminal to the front panel, and connect, in order to be consistent with the new CEF Class version.

**Comment by mmusienko** [comment]
Below is a copy of my post at http://forums.ni.com/t5/forums/editpage/board-id/5235/message-id/139 which I tried to edit enough times to flag it as required moderation (but is not visible under "items awaiting approval" in the profile).
So that it is not lost, duplicating here.

===

I am able to recreate the issue on my machine and want to provide some more details to the discussion - 
 
System configuration - LabView 2016 and 2015, latest DCAF packages (not all, but most of them) from VIPM for 2016 and 2015.
Steps to reproduse - 
- open DCAF configuration editor, create blank project.
- add cRIO target, add standard engine under cRIO, add multiple sources (Polynominal scale, scan engine, CVT, Shared library, tag select, udp broadcast)
- observe all sources display their UI as expected
- add Shared Memory module
- click on shared memory module to display its UI. observe "UI.vi for selected class is broken" error message
- click on other sources in the project. Observe all display their UI fine except for Polynomial scale and tag select modules that shows the same error message. 
I get the same error in both 2016 and 2015.
 
The Shared Memory Editor Node.lvclass:configuration UI.vi (latest from github, as well as sept 22 version) is not runnable (broken arrow). Error list is long but all of them seems to be due to ToTable.vi having terminals incompatible with its ancestor (NISE_CEF_serializeable node.lvclass:ToTable.vi).
Exact error is at ToTable.vi - This VI doesn't match other VIs in the method, Connector Pane Terminal(s) are different. All VIs that implement a method of a LabVIEW class must match Connector Panes. To correct this, compare Connector Pane of both this VI and the VI of an ancestor class that implements this method.
UIs for other affected modules (polynomial scaling and tag select, latest from github) are runnable. 
 
workaround - downgrade Shared Memory module from 1.0.1.18 to 1.0.1.12. This allows all modules to display their UIs.
 
Note that we did not experience the issue when Steve had only LabView 2015 installed. Not sure if this is somehow related to 2016?
Very interesting how the issue affect other modules (overwrites ToTable.vi in-memory???).
 
Update1: The issue is clearly related to https://github.com/LabVIEW-DCAF/SharedMemoryModule/issues/4.
I have just built and installed Shared Memory module from commit cbcbfe607f2224bc6ccfe581ffbc231bc0ffb673 and UIs work fine. When I build and install Shared Memory module from commit 8db898d36b2d96c31f3234ce8a6fe4ae136e41b2, UIs break.
 
Github issue#4 description is in line with error I am seeing on the ToTable.vi. Issue reference some "new CEF Class version". Is there an update to CEF available that we are missing? If so it would be nice to have it as a dependency for Shared Memory module so that such issues can be avoided.
Note - I have CEF v2.1.1.107 installed which seems the latest in VIPM.

**Comment by leesecho** [comment]
This issue is known, and is actually tied to an as-yet-unpublished version of the the CEF Table API (NISE_CEF_serializable node.lvclass\**ToTable.vi**). Due to the low number of users of the DCAF Shared Memory Module to date, we decided to leave this issue, which will be resolved once the new CEF is published. In the meantime, you can use the following workaround for the latest DCAF Shared Memory Module release version (currently v1.0.1.18):

1. Install the latest DCAF Shared Memory Module version from LabVIEW Tools Network.
2. Navigate to the installed library LabVIEW project (LabVIEW\vi.lib\NI\DCAF\Modules\Shared Memory\**shared memory module.lvproj**).
3. Open the project.
4. In the project, expand Shared Memory Editor Node.lvclass, and open the ToTable.vi block diagram.
5. Delete "row header" string array, and save the VI.

These steps should fix this temporary issue, and future updates of the DCAF packages will overwrite this change.

**Comment by mmusienko** [comment]
Lee,
Thanks for feedback. 
We got it up and running fine using the custom build per your suggestion and look forward for new releases in VIPM.
