### ISSUE TITLE
Feature suggestion - configurable endianness

### ISSUE THREAD

**Issue by mmusienko** [LabVIEW-DCAF/SharedMemoryModule#8]
Currently the shared memory modules writes all values in big endian format.

It is a good idea in a lot of situations to ensure compatibility, but when the module is used as a bridge to another process, one may prefer to use native (host) endianness, because both interacting parties (DCAF and another process) are guaranteed to have same endianness. Using native endianness will remove the need to do byte order conversions.

Write To Binary File function in shared memory write.vi have an input to specify endianness so the implementation is simple. 

I suggest a drop-down menu be added to the configuration tab of the UI to allow the user to select desired endianness (big, native, little).

PS - this is definitely not a critical feature to have, but rather a convenience

**Comment by ryanpoulos** [comment]
Since the module was upgraded to use direct memory read/write operations rather than File I/O, it now uses the OS native endianness.

I don't think there will be a need to add any UI elements, since the pointer operations on both ends will follow the same endianness on the same system. The File I/O allowed the endianness to be chosen, but this is no longer the case for the memory operations with the Memory Manager.
